### ISSUE TITLE
Docs on http://achille-roussel.github.io/nanomsgxx/doc are broken

### ISSUE THREAD

**Issue by ianrtracey** [achille-roussel/nanomsgxx#11]
Several of the 'See Also' links (such as nnxx::socket, nnxx:subscribe, ext.) on http://achille-roussel.github.io/nanomsgxx/doc/nnxx.3.html link to a 404 Github page.

**Comment by achille-roussel** [comment]
Yep, I think that's because I never wrote those docs :(

I don't have much time for this these days and kind of got out of the nanomsg world but I'll welcome pull requests if you want to fix it.
