### ISSUE TITLE
_LIBCPP_VERSION is not a good way to check for C++11 support

### ISSUE THREAD

**Issue by liamuk** [achille-roussel/nanomsgxx#16]
In message_streambuf, this library uses the presence of the macro _LIBCPP_VERSION to check if rvalue references are supported by the compiler.

This works only for clang. Compiling with this library using gcc and using the macro guarded functions in message_streambuf doesn't work, even if the version of gcc supports rvalue references.

**Comment by achille-roussel** [comment]
Thanks for the feedback. Honestly I think we could get rid of this check all together, it’s 2018 and compilers have been supporting C++11 for ages. 

Would you have some time to send a PR and address this issue? Feel free to suggest an alternative approach as well.

**Comment by liamuk** [comment]
I agree we can just get rid of the check. Will send a PR when I get time sometime tomorrow.

**Comment by liamuk** [comment]
resolved by merge request
