### ISSUE TITLE
Create Release

### ISSUE THREAD

**Issue by piribes** [achille-roussel/nanomsgxx#3]
Can you please provide a release on github of this package so that i can create a brew Formula to install it on mac ?

**Comment by achille-roussel** [comment]
Hello Piribes.

I'm not really familiar with how brew formulas work and I'm not sure what you mean about "provide a release on github", do you have some material I can read on the matter so I can figure it out?

**Comment by piribes** [comment]
Hi Achille, by release i mean a compressed file containing all the source code.

You can create it, as [i made with my fork of your project](https://github.com/piribes/nanomsgxx/releases), by using github web console.
You can read more [here](https://help.github.com/articles/creating-releases/), if you want.

By doing so you enable anyone to get the source code of a release by simply downloading a well known URL of a zipped file, instead of cloning the entire repository.

**Comment by achille-roussel** [comment]
OK, there's a pending pull request fixing a pretty bad bug, do you mind waiting 1 or 2 days for this to be resolved?
Then I'll take care of this.

**Comment by piribes** [comment]
Sure, thank you.

**Comment by achille-roussel** [comment]
Here you are: https://github.com/achille-roussel/nanomsgxx/releases/tag/0.1

Let me know if there's anything else you need.

**Comment by piribes** [comment]
And here is the [brew formula](https://github.com/Homebrew/homebrew/pull/49737) i was talking.

**Comment by achille-roussel** [comment]
Awesome! Thanks for your contribution :+1:

**Comment by piribes** [comment]
The previous formula was not accepted because of nanomsgxx being not so popular.
I created a [new attempt](https://github.com/Homebrew/homebrew-core/pull/7104), hope this will be merged.
